esHost: search-sitesearch-dev-ysygv3etypruskqtfow55cgfiy.us-east-1.es.amazonaws.com
esRegion: us-east-1
esService: es
RequestCountTable: ${opt:stage}-sitesearch-request-count
RequestZeroResultsTable: ${opt:stage}-sitesearch-request-zero
firebaseUrl: https://opensearch-2a0db.firebaseio.com
s3BucketName: sitesearch-svolve-dev
recrawlInterval: "18000000"
crawlConfigFile: 'sitesearch-conf/emr-config-crawl-sdk.json'
pcrawlConfigFile: 'sitesearch-conf/emr-config-pcrawl-sdk.json'
recrawlConfigFile: 'sitesearch-conf/emr-config-recrawl-sdk.json'
firebaseServiceAccount: opensearch-2a0db-firebase-adminsdk-c87oh-80d58a586e.json
stripeKey: sk_test_P4GXFh6a1i97ieWLSKpYsdt4
