HADOOP_MASTER=localhost
SITESEARCH_INSTALL_PATH=/Users/vpalan799/Documents/projects/sitesearch/build
HADOOP_HOME=${SITESEARCH_INSTALL_PATH}/hadoop

MYSQL_HOME=
MYSQL_PORT=3306
USERNAME=vpalan799

MONGO_PORT=27017

#Hadoop
#
HADOOP_NAME_SERVER=${HADOOP_MASTER}
HADOOP_NAME_SERVER_PORT=9000

#Oozie
#
OOZIE_DB_HOST=${HADOOP_MASTER}
OOZIE_DB_PORT=${MYSQL_PORT}

#NUTCH
#
NUTCH_DB_HOST=${HADOOP_MASTER}
NUTCH_DB_PORT=${MONGO_PORT}

PLUGIN_FOLDERS=/Users/vpalan799/Documents/projects/sitesearch/build/crawl-dev/plugins
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
