# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sitesearch-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 60
custom: ${file(./sls/${opt:stage}.yml)}
package:
  individually: true

functions:
  welcome: ${file(./sls/welcome.yml)}
  search: ${file(./sls/search.yml)}
  analytics: ${file(./sls/analytics.yml)}
  webhook: ${file(./sls/webhook.yml)}
  count: ${file(./sls/count.yml)}
  pages: ${file(./sls/pages.yml)}
  invoices: ${file(./sls/invoices.yml)}
  cards: ${file(./sls/cards.yml)}
  charge: ${file(./sls/charge.yml)}
  customer: ${file(./sls/customer.yml)}
  crawl: ${file(./sls/crawl.yml)}
  pcrawl: ${file(./sls/pcrawl.yml)}
  recrawlSetup: ${file(./sls/recrawlSetup.yml)}
  recrawl: ${file(./sls/recrawl.yml)}
  trial: ${file(./sls/trial.yml)}
  suspend: ${file(./sls/suspend.yml)}
  config: ${file(./sls/config.yml)}
  quote: ${file(./sls/quote.yml)}
  billing: ${file(./sls/billing.yml)}
  message: ${file(./sls/message.yml)}
  subscribeForTrial: ${file(./sls/subscribeForTrial.yml)}
